install-merlin.sh.in: Add removed abort function to script again
it got lost somewhere down the way when moving to automake.
this fix put the function back.

solves issue #9539

Signed-off-by: Mattias Ryrlén <mattiasr@op5.com>

diff --git a/install-merlin.sh.in b/install-merlin.sh.in
--- a/install-merlin.sh.in
+++ b/install-merlin.sh.in
@@ -10,6 +10,13 @@ db_name=@db_name@
 db_user=@db_user@
 db_pass=@db_pass@
 
+abort ()
+{
+	echo "$@"
+	echo "Aborting."
+	exit 1
+}
+
 db_setup ()
 {
 	mysql="mysql"
