Don't redirect all SQL output to secret file - someone might want to retrieve the errors
Change-Id: Ic6d332b20095f5cbc696d589023cb44d6bc01070

diff --git a/install-merlin.sh.in b/install-merlin.sh.in
--- a/install-merlin.sh.in
+++ b/install-merlin.sh.in
@@ -71,7 +71,7 @@ db_setup ()
 
 			# Fetch db_version and do upgrade stuff if/when needed
 			query="SELECT version FROM db_version"
-			db_version=$(eval "$mysql $db_name -BNe \"$query\"" 2>/dev/null)
+			db_version=$(eval "$mysql $db_name -BNe \"$query\"")
 
 			# Check for upgrade scripts
 			ver=$db_version
@@ -80,14 +80,14 @@ db_setup ()
 					nextver=$((ver+1))
 					f="$sqldir/update-db-${ver}to${nextver}.sql"
 					test -f "$f" || break
-					eval "$mysql $db_name" < $f 2>&1 >>/tmp/merlin-sql-upgrade.log || abort "Incremental database upgrade from version $ver to version $nextver failed!"
-					eval "$mysql $db_name -e \"UPDATE db_version SET version=$nextver\"" 2>&1 >> /tmp/merlin-sql-upgrade.log || abort "Failed to set new database version $nextver!"
+					eval "$mysql $db_name" < $f || abort "Incremental database upgrade from version $ver to version $nextver failed!"
+					eval "$mysql $db_name -e \"UPDATE db_version SET version=$nextver\"" || abort "Failed to set new database version $nextver!"
 					ver=$nextver
 				done
 			fi
 			if [ $new_install -eq 1 ]; then
 				for index in $sqldir/mysql/*-indexes.sql; do
-					eval "$mysql -f $db_name" < $index 2>&1 >>/tmp/merlin-sql-upgrade.log
+					eval "$mysql -f $db_name" < $index
 				done
 			else
 				# only check for indexes in report_data. sloppy, yes, but should be sufficient
